import type { Artwork, Product } from "@/types/content";

export const artworks: Artwork[] = [
  {
    id: "g1",
    slug: "pigmento-en-cal",
    title: "Pigmento en Cal",
    year: "2024",
    medium: "Técnica mixta",
    dimensions: "100 x 100 cm",
    imageUrl: "https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?auto=format&fit=crop&w=1400&q=80",
    excerpt: "Exploración de texturas minerales y luz sobre superficies calcáreas.",
    category: "Serie Estudio",
  },
  {
    id: "g2",
    slug: "aguada-nocturna",
    title: "Aguada Nocturna",
    year: "2024",
    medium: "Técnica mixta",
    dimensions: "100 x 100 cm",
    imageUrl: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=1400&q=80",
    excerpt: "Estudio de profundidades y sombras en la oscuridad.",
    category: "Paisaje",
  },
  {
    id: "g3",
    slug: "terracota-viva",
    title: "Terracota Viva",
    year: "2024",
    medium: "Técnica mixta",
    dimensions: "100 x 100 cm",
    imageUrl: "https://images.unsplash.com/photo-1482192596544-9eb780fc7f66?auto=format&fit=crop&w=1400&q=80",
    excerpt: "Diálogo entre el color tierra y el movimiento orgánico.",
    category: "Abstraccion",
  },
  {
    id: "g4",
    slug: "bruma-dorada",
    title: "Bruma Dorada",
    year: "2024",
    medium: "Técnica mixta",
    dimensions: "100 x 100 cm",
    imageUrl: "https://images.unsplash.com/photo-1545239351-1141bd82e8a6?auto=format&fit=crop&w=1400&q=80",
    excerpt: "Captura de la atmósfera cálida y difusa del litoral.",
    category: "Serie Costa",
  },
  {
    id: "g5",
    slug: "muro-y-sal",
    title: "Muro y Sal",
    year: "2024",
    medium: "Técnica mixta",
    dimensions: "100 x 100 cm",
    imageUrl: "https://images.unsplash.com/photo-1541961017774-22349e4a1262?auto=format&fit=crop&w=1400&q=80",
    excerpt: "La erosión del tiempo plasmada sobre el soporte artístico.",
    category: "Materia",
  },
  {
    id: "g6",
    slug: "linea-de-viento",
    title: "Linea de Viento",
    year: "2024",
    medium: "Técnica mixta",
    dimensions: "100 x 100 cm",
    imageUrl: "https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?auto=format&fit=crop&w=1400&q=80",
    excerpt: "Gesto rápido que atraviesa la composición como una ráfaga.",
    category: "Paisaje",
  },
  {
    id: "g7",
    slug: "polvo-azul",
    title: "Polvo Azul",
    year: "2024",
    medium: "Técnica mixta",
    dimensions: "100 x 100 cm",
    imageUrl: "https://images.unsplash.com/photo-1578301978693-85fa9c0320b9?auto=format&fit=crop&w=1400&q=80",
    excerpt: "Pigmentos etéreos que flotan en un espacio de calma.",
    category: "Abstraccion",
  },
  {
    id: "g8",
    slug: "naranja-de-taller",
    title: "Naranja de Taller",
    year: "2024",
    medium: "Técnica mixta",
    dimensions: "100 x 100 cm",
    imageUrl: "https://images.unsplash.com/photo-1577083165633-14ebcdb0f658?auto=format&fit=crop&w=1400&q=80",
    excerpt: "La cotidianidad del estudio transformada en vibración cromática.",
    category: "Serie Estudio",
  },
  {
    id: "g9",
    slug: "silencio-mineral",
    title: "Silencio Mineral",
    year: "2024",
    medium: "Técnica mixta",
    dimensions: "100 x 100 cm",
    imageUrl: "https://images.unsplash.com/photo-1578926288207-a90a5366759d?auto=format&fit=crop&w=1400&q=80",
    excerpt: "Composición estática que invita a la contemplación táctil.",
    category: "Materia",
  },
  {
    id: "g10",
    slug: "rastro-carmesi",
    title: "Rastro Carmesi",
    year: "2024",
    medium: "Técnica mixta",
    dimensions: "100 x 100 cm",
    imageUrl: "https://images.unsplash.com/photo-1579762593131-b8945254345c?auto=format&fit=crop&w=1400&q=80",
    excerpt: "Memoria de un gesto pasional en la orilla del mar.",
    category: "Serie Costa",
  },
  {
    id: "g11",
    slug: "horizonte-de-yeso",
    title: "Horizonte de Yeso",
    year: "2024",
    medium: "Técnica mixta",
    dimensions: "100 x 100 cm",
    imageUrl: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=1400&q=80",
    excerpt: "Límite frágil entre la tierra y el cielo infinito.",
    category: "Paisaje",
  },
];

export const products: Product[] = [
  {
    id: "p1",
    name: "Print Fine Art - Mareas Ocre",
    description: "Impresion giclee firmada, edicion limitada de 30 unidades.",
    price: 240,
    currency: "usd",
    imageUrl: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=900&q=80",
    stripePriceId: "price_placeholder_mareas_ocre",
  },
  {
    id: "p2",
    name: "Catalogo de Estudio 2026",
    description: "Publicacion de 96 paginas con proceso y archivo de obra.",
    price: 68,
    currency: "usd",
    imageUrl: "https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=900&q=80",
    stripePriceId: "price_placeholder_catalogo_2026",
  },
];

export function getArtworkBySlug(slug: string) {
  return artworks.find((artwork) => artwork.slug === slug);
}
